/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookResultCountResponse */
        BookResultCountResponse: {
            /** Book Id */
            book_id: string;
            /** Book Title */
            book_title: string;
            /** Result Count */
            result_count: number;
        };
        /** CatalogBookResponse */
        CatalogBookResponse: {
            /** Book Id */
            book_id: string;
            /** Book Sequence */
            book_sequence: number;
            /** Book Title */
            book_title: string;
            /** Povs */
            povs: string[];
        };
        /** ChunkMetadata */
        ChunkMetadata: {
            /** Book Id */
            book_id: string;
            /** Book Sequence */
            book_sequence: number;
            /** Book Title */
            book_title: string;
            /** Chapter Id */
            chapter_id: string;
            /** Chapter Sequence */
            chapter_sequence: number;
            /** Chapter Title */
            chapter_title: string;
            /** Chunk Ordinal */
            chunk_ordinal: number;
            /** Id */
            id: string;
            /** Pov */
            pov: string;
            /** Pov Ordinal */
            pov_ordinal: number;
            /** Word End */
            word_end: number;
            /** Word Start */
            word_start: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Index Configured */
            index_configured: boolean;
            /** Model Loaded */
            model_loaded: boolean;
            /** Status */
            status: string;
        };
        /** PassageFragmentResponse */
        PassageFragmentResponse: {
            /**
             * Region
             * @enum {string}
             */
            region: "before" | "focus" | "after";
            /** Text */
            text: string;
        };
        /** PassageParagraphResponse */
        PassageParagraphResponse: {
            /** Fragments */
            fragments: components["schemas"]["PassageFragmentResponse"][];
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Partial End */
            partial_end: boolean;
            /** Partial Start */
            partial_start: boolean;
        };
        /** SearchCatalogResponse */
        SearchCatalogResponse: {
            /** Books */
            books: components["schemas"]["CatalogBookResponse"][];
        };
        /** SearchPaginationResponse */
        SearchPaginationResponse: {
            /** Has Next */
            has_next: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Book */
            book?: string | null;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical";
            /** Page */
            page?: number | null;
            /** Page Size */
            page_size?: number | null;
            /** Pov */
            pov?: string | null;
            /** Povs */
            povs?: string[] | null;
            /** Query */
            query: string;
            /** Top */
            top?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Book Counts */
            book_counts?: components["schemas"]["BookResultCountResponse"][];
            /** Cached */
            cached: boolean;
            /** Duration Ms */
            duration_ms: number;
            pagination?: components["schemas"]["SearchPaginationResponse"] | null;
            /** Query */
            query: string;
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["SearchResultResponse"][];
        };
        /** SearchResultResponse */
        SearchResultResponse: {
            chunk: components["schemas"]["ChunkMetadata"];
            /** Context After */
            context_after?: string | null;
            /** Context Before */
            context_before?: string | null;
            /** Context Word End */
            context_word_end?: number | null;
            /** Context Word Start */
            context_word_start?: number | null;
            /** Excerpt */
            excerpt: string;
            /** Paragraphs */
            paragraphs?: components["schemas"]["PassageParagraphResponse"][];
            /** Rank */
            rank: number;
            /** Retrieval */
            retrieval?: {
                [key: string]: unknown;
            } | null;
            /** Score */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    catalog_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCatalogResponse"];
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
